/* Generated from src/js/url.js by tools/embed_js.py: do not edit. */
static const char k_url_js[] =
    "(function () {\n"
    "  'use strict';\n"
    "  const EOF = -1;\n"
    "  const fromCP = String.fromCodePoint;\n"
    "  const SPECIAL = { __proto__: null, 'ftp': 21, 'file': null, 'http': 80, 'https': 443, 'ws': 80, 'wss': 443 };\n"
    "  const isSpecialScheme = s => s in SPECIAL;\n"
    "  const isAlpha = c => (c >= 0x41 && c <= 0x5A) || (c >= 0x61 && c <= 0x7A);\n"
    "  const isDigit = c => c >= 0x30 && c <= 0x39;\n"
    "  const isHex = c => isDigit(c) || (c >= 0x41 && c <= 0x46) || (c >= 0x61 && c <= 0x66);\n"
    "  const isAlnum = c => isAlpha(c) || isDigit(c);\n"
    "  const hexVal = c => (c <= 0x39 ? c - 0x30 : (c | 0x20) - 0x61 + 10);\n"
    "  const HEX = '0123456789ABCDEF';\n"
    "  function usv(v) {\n"
    "    const s = String(v); // a Symbol throws TypeError, as WebIDL says\n"
    "    let i = 0;\n"
    "    for (; i < s.length; i++) {\n"
    "      const c = s.charCodeAt(i);\n"
    "      if (c < 0xD800 || c > 0xDFFF) continue;\n"
    "      const d = i + 1 < s.length ? s.charCodeAt(i + 1) : 0;\n"
    "      if (c <= 0xDBFF && d >= 0xDC00 && d <= 0xDFFF) { i++; continue; }\n"
    "      break;\n"
    "    }\n"
    "    if (i >= s.length) return s;\n"
    "    let r = s.slice(0, i);\n"
    "    for (; i < s.length; i++) {\n"
    "      const c = s.charCodeAt(i);\n"
    "      const d = i + 1 < s.length ? s.charCodeAt(i + 1) : 0;\n"
    "      if (c >= 0xD800 && c <= 0xDBFF && d >= 0xDC00 && d <= 0xDFFF) { r += s[i] + s[i + 1]; i++; }\n"
    "      else if (c >= 0xD800 && c <= 0xDFFF) r += '\\uFFFD';\n"
    "      else r += s[i];\n"
    "    }\n"
    "    return r;\n"
    "  }\n"
    "  function codePoints(s) {\n"
    "    const a = [];\n"
    "    for (const ch of s) a.push(ch.codePointAt(0));\n"
    "    return a;\n"
    "  }\n"
    "  function utf8Bytes(cp, out) {\n"
    "    if (cp >= 0xD800 && cp <= 0xDFFF) cp = 0xFFFD;\n"
    "    if (cp < 0x80) out.push(cp);\n"
    "    else if (cp < 0x800) out.push(0xC0 | (cp >> 6), 0x80 | (cp & 63));\n"
    "    else if (cp < 0x10000) out.push(0xE0 | (cp >> 12), 0x80 | ((cp >> 6) & 63), 0x80 | (cp & 63));\n"
    "    else out.push(0xF0 | (cp >> 18), 0x80 | ((cp >> 12) & 63), 0x80 | ((cp >> 6) & 63), 0x80 | (cp & 63));\n"
    "    return out;\n"
    "  }\n"
    "  function utf8Encode(s) {\n"
    "    const out = [];\n"
    "    for (const ch of s) utf8Bytes(ch.codePointAt(0), out);\n"
    "    return out;\n"
    "  }\n"
    "  function utf8Decode(bytes) {\n"
    "    let out = '', need = 0, cp = 0, lower = 0x80, upper = 0xBF;\n"
    "    for (let i = 0; i < bytes.length; i++) {\n"
    "      const b = bytes[i];\n"
    "      if (need === 0) {\n"
    "        if (b <= 0x7F) out += String.fromCharCode(b);\n"
    "        else if (b >= 0xC2 && b <= 0xDF) { need = 1; cp = b & 0x1F; }\n"
    "        else if (b >= 0xE0 && b <= 0xEF) { if (b === 0xE0) lower = 0xA0; if (b === 0xED) upper = 0x9F; need = 2; cp = b & 0xF; }\n"
    "        else if (b >= 0xF0 && b <= 0xF4) { if (b === 0xF0) lower = 0x90; if (b === 0xF4) upper = 0x8F; need = 3; cp = b & 7; }\n"
    "        else out += '\\uFFFD';\n"
    "        continue;\n"
    "      }\n"
    "      if (b < lower || b > upper) {\n"
    "        need = 0; lower = 0x80; upper = 0xBF;\n"
    "        out += '\\uFFFD';\n"
    "        i--; // the byte starts over\n"
    "        continue;\n"
    "      }\n"
    "      lower = 0x80; upper = 0xBF;\n"
    "      cp = (cp << 6) | (b & 0x3F);\n"
    "      if (--need === 0) out += fromCP(cp);\n"
    "    }\n"
    "    if (need) out += '\\uFFFD';\n"
    "    return out;\n"
    "  }\n"
    "  function percentDecode(bytes) {\n"
    "    const out = [];\n"
    "    for (let i = 0; i < bytes.length; i++) {\n"
    "      const b = bytes[i];\n"
    "      if (b === 0x25 && i + 2 < bytes.length && isHex(bytes[i + 1]) && isHex(bytes[i + 2])) {\n"
    "        out.push(hexVal(bytes[i + 1]) * 16 + hexVal(bytes[i + 2]));\n"
    "        i += 2;\n"
    "      } else out.push(b);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  const inC0 = c => c < 0x20 || c > 0x7E;\n"
    "  const inFragment = c => inC0(c) || c === 0x20 || c === 0x22 || c === 0x3C || c === 0x3E || c === 0x60;\n"
    "  const inQuery = c => inC0(c) || c === 0x20 || c === 0x22 || c === 0x23 || c === 0x3C || c === 0x3E;\n"
    "  const inSpecialQuery = c => inQuery(c) || c === 0x27;\n"
    "  const inPath = c => inQuery(c) || c === 0x3F || c === 0x5E || c === 0x60 || c === 0x7B || c === 0x7D;\n"
    "  const inUserinfo = c => inPath(c) || c === 0x2F || c === 0x3A || c === 0x3B || c === 0x3D || c === 0x40 ||\n"
    "                          (c >= 0x5B && c <= 0x5E) || c === 0x7C;\n"
    "  const inComponent = c => inUserinfo(c) || (c >= 0x24 && c <= 0x26) || c === 0x2B || c === 0x2C;\n"
    "  const inForm = c => inComponent(c) || c === 0x21 || (c >= 0x27 && c <= 0x29) || c === 0x7E;\n"
    "  const pctByte = b => '%' + HEX[b >> 4] + HEX[b & 15];\n"
    "  function encodeCP(cp, inSet) {\n"
    "    if (!inSet(cp)) return fromCP(cp);\n"
    "    let s = '';\n"
    "    for (const b of utf8Bytes(cp, [])) s += pctByte(b);\n"
    "    return s;\n"
    "  }\n"
    "  function encodeString(s, inSet) {\n"
    "    let out = '';\n"
    "    for (const ch of s) out += encodeCP(ch.codePointAt(0), inSet);\n"
    "    return out;\n"
    "  }\n"
    "  const forbiddenHost = c => c === 0 || c === 9 || c === 0xA || c === 0xD || c === 0x20 || c === 0x23 || c === 0x2F ||\n"
    "                             c === 0x3A || c === 0x3C || c === 0x3E || c === 0x3F || c === 0x40 || c === 0x5B ||\n"
    "                             c === 0x5C || c === 0x5D || c === 0x5E || c === 0x7C;\n"
    "  const forbiddenDomain = c => forbiddenHost(c) || c <= 0x1F || c === 0x25 || c === 0x7F;\n"
    "  function parseIPv6(s) {\n"
    "    const input = codePoints(s), len = input.length;\n"
    "    const address = [0, 0, 0, 0, 0, 0, 0, 0];\n"
    "    let piece = 0, compress = null, p = 0;\n"
    "    const at = i => (i < len ? input[i] : EOF);\n"
    "    if (at(p) === 0x3A) {\n"
    "      if (at(p + 1) !== 0x3A) return null;\n"
    "      p += 2;\n"
    "      piece++;\n"
    "      compress = piece;\n"
    "    }\n"
    "    while (at(p) !== EOF) {\n"
    "      if (piece === 8) return null;\n"
    "      if (at(p) === 0x3A) {\n"
    "        if (compress !== null) return null;\n"
    "        p++;\n"
    "        piece++;\n"
    "        compress = piece;\n"
    "        continue;\n"
    "      }\n"
    "      let value = 0, length = 0;\n"
    "      while (length < 4 && isHex(at(p))) { value = value * 16 + hexVal(at(p)); p++; length++; }\n"
    "      if (at(p) === 0x2E) {\n"
    "        if (length === 0) return null;\n"
    "        p -= length;\n"
    "        if (piece > 6) return null;\n"
    "        let seen = 0;\n"
    "        while (at(p) !== EOF) {\n"
    "          let v4 = null;\n"
    "          if (seen > 0) {\n"
    "            if (at(p) === 0x2E && seen < 4) p++;\n"
    "            else return null;\n"
    "          }\n"
    "          if (!isDigit(at(p))) return null;\n"
    "          while (isDigit(at(p))) {\n"
    "            const n = at(p) - 0x30;\n"
    "            if (v4 === null) v4 = n;\n"
    "            else if (v4 === 0) return null;\n"
    "            else v4 = v4 * 10 + n;\n"
    "            if (v4 > 255) return null;\n"
    "            p++;\n"
    "          }\n"
    "          address[piece] = address[piece] * 0x100 + v4;\n"
    "          seen++;\n"
    "          if (seen === 2 || seen === 4) piece++;\n"
    "        }\n"
    "        if (seen !== 4) return null;\n"
    "        break;\n"
    "      } else if (at(p) === 0x3A) {\n"
    "        p++;\n"
    "        if (at(p) === EOF) return null;\n"
    "      } else if (at(p) !== EOF) return null;\n"
    "      address[piece] = value;\n"
    "      piece++;\n"
    "    }\n"
    "    if (compress !== null) {\n"
    "      let swaps = piece - compress;\n"
    "      piece = 7;\n"
    "      while (piece !== 0 && swaps > 0) {\n"
    "        const t = address[piece];\n"
    "        address[piece] = address[compress + swaps - 1];\n"
    "        address[compress + swaps - 1] = t;\n"
    "        piece--;\n"
    "        swaps--;\n"
    "      }\n"
    "    } else if (piece !== 8) return null;\n"
    "    return address;\n"
    "  }\n"
    "  function serializeIPv6(a) {\n"
    "    let best = -1, bestLen = 1;\n"
    "    for (let i = 0; i < 8;) {\n"
    "      if (a[i] !== 0) { i++; continue; }\n"
    "      let j = i;\n"
    "      while (j < 8 && a[j] === 0) j++;\n"
    "      if (j - i > bestLen) { best = i; bestLen = j - i; }\n"
    "      i = j;\n"
    "    }\n"
    "    let out = '', ignore0 = false;\n"
    "    for (let i = 0; i < 8; i++) {\n"
    "      if (ignore0 && a[i] === 0) continue;\n"
    "      ignore0 = false;\n"
    "      if (best === i) {\n"
    "        out += i === 0 ? '::' : ':';\n"
    "        ignore0 = true;\n"
    "        continue;\n"
    "      }\n"
    "      out += a[i].toString(16);\n"
    "      if (i !== 7) out += ':';\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  function parseIPv4Number(s) {\n"
    "    if (s === '') return null;\n"
    "    let r = 10;\n"
    "    if (s.length >= 2 && s[0] === '0' && (s[1] === 'x' || s[1] === 'X')) { s = s.slice(2); r = 16; }\n"
    "    else if (s.length >= 2 && s[0] === '0') { s = s.slice(1); r = 8; }\n"
    "    if (s === '') return 0;\n"
    "    let n = 0;\n"
    "    for (let i = 0; i < s.length; i++) {\n"
    "      const c = s.charCodeAt(i);\n"
    "      const d = isDigit(c) ? c - 0x30 : isHex(c) ? hexVal(c) : 99;\n"
    "      if (d >= r) return null;\n"
    "      n = n * r + d;\n"
    "    }\n"
    "    return n;\n"
    "  }\n"
    "  function endsInNumber(s) {\n"
    "    const parts = s.split('.');\n"
    "    if (parts[parts.length - 1] === '') {\n"
    "      if (parts.length === 1) return false;\n"
    "      parts.pop();\n"
    "    }\n"
    "    const last = parts[parts.length - 1];\n"
    "    if (last !== '' && /^[0-9]+$/.test(last)) return true;\n"
    "    return parseIPv4Number(last) !== null;\n"
    "  }\n"
    "  function parseIPv4(s) {\n"
    "    const parts = s.split('.');\n"
    "    if (parts[parts.length - 1] === '' && parts.length > 1) parts.pop();\n"
    "    if (parts.length > 4) return null;\n"
    "    const nums = [];\n"
    "    for (const p of parts) {\n"
    "      const n = parseIPv4Number(p);\n"
    "      if (n === null) return null;\n"
    "      nums.push(n);\n"
    "    }\n"
    "    for (let i = 0; i < nums.length - 1; i++) if (nums[i] > 255) return null;\n"
    "    if (nums[nums.length - 1] >= 256 ** (5 - nums.length)) return null;\n"
    "    let v = nums[nums.length - 1];\n"
    "    for (let i = 0; i < nums.length - 1; i++) v += nums[i] * 256 ** (3 - i);\n"
    "    const o = [];\n"
    "    for (let i = 0; i < 4; i++) { o.unshift(v % 256); v = Math.floor(v / 256); }\n"
    "    return o.join('.');\n"
    "  }\n"
    "  function punycodeValid(s) {\n"
    "    const base = 36, tmin = 1, tmax = 26, skew = 38, damp = 700;\n"
    "    let n = 128, i = 0, bias = 72, out = 0;\n"
    "    let b = s.lastIndexOf('-');\n"
    "    if (b < 0) b = 0;\n"
    "    for (let j = 0; j < b; j++) if (s.charCodeAt(j) >= 0x80) return false;\n"
    "    out = b;\n"
    "    for (let k = b > 0 ? b + 1 : 0; k < s.length;) {\n"
    "      const oldi = i;\n"
    "      let w = 1;\n"
    "      for (let t = base; ; t += base) {\n"
    "        if (k >= s.length) return false;\n"
    "        const c = s.charCodeAt(k++);\n"
    "        const d = c - 48 < 10 ? c - 22 : c - 65 < 26 ? c - 65 : c - 97 < 26 ? c - 97 : base;\n"
    "        if (d >= base) return false;\n"
    "        i += d * w;\n"
    "        if (i > 0x7FFFFFFF) return false;\n"
    "        const th = t <= bias ? tmin : t >= bias + tmax ? tmax : t - bias;\n"
    "        if (d < th) break;\n"
    "        w *= base - th;\n"
    "        if (w > 0x7FFFFFFF) return false;\n"
    "      }\n"
    "      out++;\n"
    "      let delta = oldi === 0 ? Math.floor((i - oldi) / damp) : (i - oldi) >> 1;\n"
    "      delta += Math.floor(delta / out);\n"
    "      let kk = 0;\n"
    "      while (delta > ((base - tmin) * tmax) >> 1) { delta = Math.floor(delta / (base - tmin)); kk += base; }\n"
    "      bias = kk + Math.floor(((base - tmin + 1) * delta) / (delta + skew));\n"
    "      n += Math.floor(i / out);\n"
    "      i %= out;\n"
    "      if (n > 0x10FFFF || (n >= 0xD800 && n <= 0xDFFF)) return false;\n"
    "      i++;\n"
    "    }\n"
    "    return true;\n"
    "  }\n"
    "  function punycodeEncode(cps) {\n"
    "    const base = 36, tmin = 1, tmax = 26, skew = 38, damp = 700;\n"
    "    const digit = d => String.fromCharCode(d < 26 ? d + 97 : d + 22);\n"
    "    let n = 128, delta = 0, bias = 72, out = '';\n"
    "    for (const c of cps) if (c < 0x80) out += String.fromCharCode(c);\n"
    "    const b = out.length;\n"
    "    let h = b;\n"
    "    if (b > 0) out += '-';\n"
    "    while (h < cps.length) {\n"
    "      let m = 0x110000;\n"
    "      for (const c of cps) if (c >= n && c < m) m = c;\n"
    "      delta += (m - n) * (h + 1);\n"
    "      n = m;\n"
    "      for (const c of cps) {\n"
    "        if (c < n) delta++;\n"
    "        if (c !== n) continue;\n"
    "        let q = delta;\n"
    "        for (let k = base; ; k += base) {\n"
    "          const t = k <= bias ? tmin : k >= bias + tmax ? tmax : k - bias;\n"
    "          if (q < t) break;\n"
    "          out += digit(t + ((q - t) % (base - t)));\n"
    "          q = Math.floor((q - t) / (base - t));\n"
    "        }\n"
    "        out += digit(q);\n"
    "        let d = h === b ? Math.floor(delta / damp) : delta >> 1;\n"
    "        d += Math.floor(d / (h + 1));\n"
    "        let kk = 0;\n"
    "        while (d > ((base - tmin) * tmax) >> 1) { d = Math.floor(d / (base - tmin)); kk += base; }\n"
    "        bias = kk + Math.floor(((base - tmin + 1) * d) / (d + skew));\n"
    "        delta = 0;\n"
    "        h++;\n"
    "      }\n"
    "      delta++;\n"
    "      n++;\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  function mapDomainChar(c) {\n"
    "    if (c === 0xAD || c === 0x34F || (c >= 0x180B && c <= 0x180F) || c === 0x200B || c === 0x2060 || c === 0xFEFF ||\n"
    "        (c >= 0xFE00 && c <= 0xFE0F)) return '';\n"
    "    if (c === 0x3002 || c === 0xFF0E || c === 0xFF61) return '.';\n"
    "    if (c >= 0xFF01 && c <= 0xFF5E) return String.fromCharCode(c - 0xFEE0);\n"
    "    if (c >= 0x1D400 && c <= 0x1D6A3) { const i = (c - 0x1D400) % 52; return String.fromCharCode(i < 26 ? 0x41 + i : 0x61 + i - 26); }\n"
    "    if (c >= 0x1D7CE && c <= 0x1D7FF) return String.fromCharCode(0x30 + (c - 0x1D7CE) % 10);\n"
    "    if (c === 0xA0 || c === 0x3000 || (c >= 0x2000 && c <= 0x200A)) return ' ';\n"
    "    if ((c >= 0x80 && c <= 0x9F) || (c >= 0xD800 && c <= 0xDFFF) || (c >= 0xE000 && c <= 0xF8FF) ||\n"
    "        (c >= 0xFDD0 && c <= 0xFDEF) || (c & 0xFFFE) === 0xFFFE || c === 0xFFFD || c === 0x2028 || c === 0x2029 ||\n"
    "        (c >= 0x200C && c <= 0x200F) || (c >= 0x202A && c <= 0x202E))\n"
    "      return null;\n"
    "    return fromCP(c);\n"
    "  }\n"
    "  function domainToASCII(domain) {\n"
    "    let mapped = '';\n"
    "    for (const ch of domain) {\n"
    "      const cp = ch.codePointAt(0);\n"
    "      if (cp < 0x80) { mapped += ch; continue; }\n"
    "      const m = mapDomainChar(cp);\n"
    "      if (m === null) return null;\n"
    "      mapped += m;\n"
    "    }\n"
    "    const labels = mapped.toLowerCase().split('.');\n"
    "    for (let i = 0; i < labels.length; i++) {\n"
    "      const label = labels[i];\n"
    "      if (label.startsWith('xn--')) {\n"
    "        if (!punycodeValid(label.slice(4))) return null;\n"
    "      } else if (/[^\\x00-\\x7f]/.test(label)) {\n"
    "        labels[i] = 'xn--' + punycodeEncode(codePoints(label));\n"
    "      }\n"
    "    }\n"
    "    const result = labels.join('.');\n"
    "    if (result === '') return null;\n"
    "    for (let i = 0; i < result.length; i++) if (forbiddenDomain(result.charCodeAt(i))) return null;\n"
    "    return result;\n"
    "  }\n"
    "  function parseHost(input, isOpaque) {\n"
    "    if (input[0] === '[') {\n"
    "      if (input[input.length - 1] !== ']') return null;\n"
    "      const a = parseIPv6(input.slice(1, -1));\n"
    "      return a === null ? null : '[' + serializeIPv6(a) + ']';\n"
    "    }\n"
    "    if (isOpaque) {\n"
    "      for (const ch of input) if (forbiddenHost(ch.codePointAt(0))) return null;\n"
    "      return encodeString(input, inC0);\n"
    "    }\n"
    "    const domain = utf8Decode(percentDecode(utf8Encode(input)));\n"
    "    const ascii = domainToASCII(domain);\n"
    "    if (ascii === null) return null;\n"
    "    if (endsInNumber(ascii)) return parseIPv4(ascii);\n"
    "    return ascii;\n"
    "  }\n"
    "  const S_SCHEME_START = 1, S_SCHEME = 2, S_NO_SCHEME = 3, S_SPECIAL_RELATIVE_OR_AUTHORITY = 4,\n"
    "        S_PATH_OR_AUTHORITY = 5, S_RELATIVE = 6, S_RELATIVE_SLASH = 7, S_SPECIAL_AUTHORITY_SLASHES = 8,\n"
    "        S_SPECIAL_AUTHORITY_IGNORE_SLASHES = 9, S_AUTHORITY = 10, S_HOST = 11, S_HOSTNAME = 12, S_PORT = 13,\n"
    "        S_FILE = 14, S_FILE_SLASH = 15, S_FILE_HOST = 16, S_PATH_START = 17, S_PATH = 18, S_OPAQUE_PATH = 19,\n"
    "        S_QUERY = 20, S_FRAGMENT = 21;\n"
    "  const FAILURE = null;\n"
    "  function newRecord() {\n"
    "    return { scheme: '', username: '', password: '', host: null, port: null, path: [], query: null, fragment: null };\n"
    "  }\n"
    "  const isSpecial = u => isSpecialScheme(u.scheme);\n"
    "  const hasOpaquePath = u => typeof u.path === 'string';\n"
    "  const includesCredentials = u => u.username !== '' || u.password !== '';\n"
    "  const cannotHaveCredentialsOrPort = u => u.host === null || u.host === '' || u.scheme === 'file';\n"
    "  const isDriveLetter = (s, normalized) =>\n"
    "    s.length === 2 && isAlpha(s.charCodeAt(0)) && (s[1] === ':' || (!normalized && s[1] === '|'));\n"
    "  function startsWithDrive(cps, i) {\n"
    "    if (cps.length - i < 2 || !isAlpha(cps[i]) || (cps[i + 1] !== 0x3A && cps[i + 1] !== 0x7C)) return false;\n"
    "    if (cps.length - i === 2) return true;\n"
    "    const c = cps[i + 2];\n"
    "    return c === 0x2F || c === 0x5C || c === 0x3F || c === 0x23;\n"
    "  }\n"
    "  function shortenPath(u) {\n"
    "    const path = u.path;\n"
    "    if (u.scheme === 'file' && path.length === 1 && isDriveLetter(path[0], true)) return;\n"
    "    path.pop();\n"
    "  }\n"
    "  const isSingleDot = s => s === '.' || s.toLowerCase() === '%2e';\n"
    "  const isDoubleDot = s => {\n"
    "    s = s.toLowerCase();\n"
    "    return s === '..' || s === '.%2e' || s === '%2e.' || s === '%2e%2e';\n"
    "  };\n"
    "  function clonePath(p) { return typeof p === 'string' ? p : p.slice(); }\n"
    "  function basicParse(input, base, url, override) {\n"
    "    if (!url) {\n"
    "      url = newRecord();\n"
    "      input = input.replace(/^[\\u0000- ]+|[\\u0000- ]+$/g, '');\n"
    "    }\n"
    "    input = input.replace(/[\\t\\n\\r]/g, '');\n"
    "    let state = override || S_SCHEME_START;\n"
    "    let buffer = '', atSign = false, inBrackets = false, passwordToken = false;\n"
    "    const cps = codePoints(input), len = cps.length;\n"
    "    const rest = (p, cp) => p + 1 < len && cps[p + 1] === cp;\n"
    "    for (let p = 0; ; p++) {\n"
    "      const c = p < len ? cps[p] : EOF;\n"
    "      const special = isSpecial(url);\n"
    "      switch (state) {\n"
    "        case S_SCHEME_START:\n"
    "          if (isAlpha(c)) { buffer += String.fromCharCode(c | 0x20); state = S_SCHEME; }\n"
    "          else if (!override) { state = S_NO_SCHEME; p--; }\n"
    "          else return FAILURE;\n"
    "          break;\n"
    "        case S_SCHEME:\n"
    "          if (isAlnum(c) || c === 0x2B || c === 0x2D || c === 0x2E) {\n"
    "            buffer += String.fromCharCode(c >= 0x41 && c <= 0x5A ? c | 0x20 : c);\n"
    "          } else if (c === 0x3A) {\n"
    "            if (override) {\n"
    "              if (isSpecialScheme(url.scheme) !== isSpecialScheme(buffer)) return url;\n"
    "              if ((includesCredentials(url) || url.port !== null) && buffer === 'file') return url;\n"
    "              if (url.scheme === 'file' && url.host === '') return url;\n"
    "            }\n"
    "            url.scheme = buffer;\n"
    "            if (override) {\n"
    "              if (url.port === SPECIAL[url.scheme]) url.port = null;\n"
    "              return url;\n"
    "            }\n"
    "            buffer = '';\n"
    "            if (url.scheme === 'file') state = S_FILE;\n"
    "            else if (isSpecial(url) && base && base.scheme === url.scheme) state = S_SPECIAL_RELATIVE_OR_AUTHORITY;\n"
    "            else if (isSpecial(url)) state = S_SPECIAL_AUTHORITY_SLASHES;\n"
    "            else if (rest(p, 0x2F)) { state = S_PATH_OR_AUTHORITY; p++; }\n"
    "            else { url.path = ''; state = S_OPAQUE_PATH; }\n"
    "          } else if (!override) {\n"
    "            buffer = '';\n"
    "            state = S_NO_SCHEME;\n"
    "            p = -1; // start over\n"
    "          } else return FAILURE;\n"
    "          break;\n"
    "        case S_NO_SCHEME:\n"
    "          if (!base || (hasOpaquePath(base) && c !== 0x23)) return FAILURE;\n"
    "          if (hasOpaquePath(base) && c === 0x23) {\n"
    "            url.scheme = base.scheme;\n"
    "            url.path = clonePath(base.path);\n"
    "            url.query = base.query;\n"
    "            url.fragment = '';\n"
    "            state = S_FRAGMENT;\n"
    "          } else if (base.scheme !== 'file') { state = S_RELATIVE; p--; }\n"
    "          else { state = S_FILE; p--; }\n"
    "          break;\n"
    "        case S_SPECIAL_RELATIVE_OR_AUTHORITY:\n"
    "          if (c === 0x2F && rest(p, 0x2F)) { state = S_SPECIAL_AUTHORITY_IGNORE_SLASHES; p++; }\n"
    "          else { state = S_RELATIVE; p--; }\n"
    "          break;\n"
    "        case S_PATH_OR_AUTHORITY:\n"
    "          if (c === 0x2F) state = S_AUTHORITY;\n"
    "          else { state = S_PATH; p--; }\n"
    "          break;\n"
    "        case S_RELATIVE:\n"
    "          url.scheme = base.scheme;\n"
    "          if (c === 0x2F) state = S_RELATIVE_SLASH;\n"
    "          else if (isSpecial(url) && c === 0x5C) state = S_RELATIVE_SLASH;\n"
    "          else {\n"
    "            url.username = base.username;\n"
    "            url.password = base.password;\n"
    "            url.host = base.host;\n"
    "            url.port = base.port;\n"
    "            url.path = clonePath(base.path);\n"
    "            url.query = base.query;\n"
    "            if (c === 0x3F) { url.query = ''; state = S_QUERY; }\n"
    "            else if (c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "            else if (c !== EOF) {\n"
    "              url.query = null;\n"
    "              shortenPath(url);\n"
    "              state = S_PATH;\n"
    "              p--;\n"
    "            }\n"
    "          }\n"
    "          break;\n"
    "        case S_RELATIVE_SLASH:\n"
    "          if (special && (c === 0x2F || c === 0x5C)) state = S_SPECIAL_AUTHORITY_IGNORE_SLASHES;\n"
    "          else if (c === 0x2F) state = S_AUTHORITY;\n"
    "          else {\n"
    "            url.username = base.username;\n"
    "            url.password = base.password;\n"
    "            url.host = base.host;\n"
    "            url.port = base.port;\n"
    "            state = S_PATH;\n"
    "            p--;\n"
    "          }\n"
    "          break;\n"
    "        case S_SPECIAL_AUTHORITY_SLASHES:\n"
    "          if (c === 0x2F && rest(p, 0x2F)) { state = S_SPECIAL_AUTHORITY_IGNORE_SLASHES; p++; }\n"
    "          else { state = S_SPECIAL_AUTHORITY_IGNORE_SLASHES; p--; }\n"
    "          break;\n"
    "        case S_SPECIAL_AUTHORITY_IGNORE_SLASHES:\n"
    "          if (c !== 0x2F && c !== 0x5C) { state = S_AUTHORITY; p--; }\n"
    "          break;\n"
    "        case S_AUTHORITY:\n"
    "          if (c === 0x40) {\n"
    "            if (atSign) buffer = '%40' + buffer;\n"
    "            atSign = true;\n"
    "            for (const ch of buffer) {\n"
    "              const cp = ch.codePointAt(0);\n"
    "              if (cp === 0x3A && !passwordToken) { passwordToken = true; continue; }\n"
    "              const enc = encodeCP(cp, inUserinfo);\n"
    "              if (passwordToken) url.password += enc;\n"
    "              else url.username += enc;\n"
    "            }\n"
    "            buffer = '';\n"
    "          } else if (c === EOF || c === 0x2F || c === 0x3F || c === 0x23 || (special && c === 0x5C)) {\n"
    "            if (atSign && buffer === '') return FAILURE;\n"
    "            p -= codePoints(buffer).length + 1;\n"
    "            buffer = '';\n"
    "            state = S_HOST;\n"
    "          } else buffer += fromCP(c);\n"
    "          break;\n"
    "        case S_HOST:\n"
    "        case S_HOSTNAME:\n"
    "          if (override && url.scheme === 'file') { p--; state = S_FILE_HOST; }\n"
    "          else if (c === 0x3A && !inBrackets) {\n"
    "            if (buffer === '') return FAILURE;\n"
    "            if (override === S_HOSTNAME) return FAILURE;\n"
    "            const host = parseHost(buffer, !special);\n"
    "            if (host === null) return FAILURE;\n"
    "            url.host = host;\n"
    "            buffer = '';\n"
    "            state = S_PORT;\n"
    "          } else if (c === EOF || c === 0x2F || c === 0x3F || c === 0x23 || (special && c === 0x5C)) {\n"
    "            p--;\n"
    "            if (special && buffer === '') return FAILURE;\n"
    "            if (override && buffer === '' && (includesCredentials(url) || url.port !== null)) return FAILURE;\n"
    "            const host = parseHost(buffer, !special);\n"
    "            if (host === null) return FAILURE;\n"
    "            url.host = host;\n"
    "            buffer = '';\n"
    "            state = S_PATH_START;\n"
    "            if (override) return url;\n"
    "          } else {\n"
    "            if (c === 0x5B) inBrackets = true;\n"
    "            if (c === 0x5D) inBrackets = false;\n"
    "            buffer += fromCP(c);\n"
    "          }\n"
    "          break;\n"
    "        case S_PORT:\n"
    "          if (isDigit(c)) buffer += String.fromCharCode(c);\n"
    "          else if (c === EOF || c === 0x2F || c === 0x3F || c === 0x23 || (special && c === 0x5C) || override) {\n"
    "            if (buffer !== '') {\n"
    "              const port = Number(buffer);\n"
    "              if (port > 65535) return FAILURE;\n"
    "              url.port = port === SPECIAL[url.scheme] ? null : port;\n"
    "              buffer = '';\n"
    "              if (override) return url;\n"
    "            }\n"
    "            if (override) return FAILURE;\n"
    "            state = S_PATH_START;\n"
    "            p--;\n"
    "          } else return FAILURE;\n"
    "          break;\n"
    "        case S_FILE:\n"
    "          url.scheme = 'file';\n"
    "          url.host = '';\n"
    "          if (c === 0x2F || c === 0x5C) state = S_FILE_SLASH;\n"
    "          else if (base && base.scheme === 'file') {\n"
    "            url.host = base.host;\n"
    "            url.path = clonePath(base.path);\n"
    "            url.query = base.query;\n"
    "            if (c === 0x3F) { url.query = ''; state = S_QUERY; }\n"
    "            else if (c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "            else if (c !== EOF) {\n"
    "              url.query = null;\n"
    "              if (!startsWithDrive(cps, p)) shortenPath(url);\n"
    "              else url.path = [];\n"
    "              state = S_PATH;\n"
    "              p--;\n"
    "            }\n"
    "          } else { state = S_PATH; p--; }\n"
    "          break;\n"
    "        case S_FILE_SLASH:\n"
    "          if (c === 0x2F || c === 0x5C) state = S_FILE_HOST;\n"
    "          else {\n"
    "            if (base && base.scheme === 'file') {\n"
    "              url.host = base.host;\n"
    "              if (!startsWithDrive(cps, p) && base.path.length > 0 && isDriveLetter(base.path[0], true))\n"
    "                url.path.push(base.path[0]);\n"
    "            }\n"
    "            state = S_PATH;\n"
    "            p--;\n"
    "          }\n"
    "          break;\n"
    "        case S_FILE_HOST:\n"
    "          if (c === EOF || c === 0x2F || c === 0x5C || c === 0x3F || c === 0x23) {\n"
    "            p--;\n"
    "            if (!override && isDriveLetter(buffer, false)) state = S_PATH; // buffer stays: the path's first segment\n"
    "            else if (buffer === '') {\n"
    "              url.host = '';\n"
    "              if (override) return url;\n"
    "              state = S_PATH_START;\n"
    "            } else {\n"
    "              let host = parseHost(buffer, !special);\n"
    "              if (host === null) return FAILURE;\n"
    "              if (host === 'localhost') host = '';\n"
    "              url.host = host;\n"
    "              if (override) return url;\n"
    "              buffer = '';\n"
    "              state = S_PATH_START;\n"
    "            }\n"
    "          } else buffer += fromCP(c);\n"
    "          break;\n"
    "        case S_PATH_START:\n"
    "          if (special) {\n"
    "            state = S_PATH;\n"
    "            if (c !== 0x2F && c !== 0x5C) p--;\n"
    "          } else if (!override && c === 0x3F) { url.query = ''; state = S_QUERY; }\n"
    "          else if (!override && c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "          else if (c !== EOF) {\n"
    "            state = S_PATH;\n"
    "            if (c !== 0x2F) p--;\n"
    "          } else if (override && url.host === null) url.path.push('');\n"
    "          break;\n"
    "        case S_PATH:\n"
    "          if (c === EOF || c === 0x2F || (special && c === 0x5C) || (!override && (c === 0x3F || c === 0x23))) {\n"
    "            const slash = c === 0x2F || (special && c === 0x5C);\n"
    "            if (isDoubleDot(buffer)) {\n"
    "              shortenPath(url);\n"
    "              if (!slash) url.path.push('');\n"
    "            } else if (isSingleDot(buffer) && !slash) url.path.push('');\n"
    "            else if (!isSingleDot(buffer)) {\n"
    "              if (url.scheme === 'file' && url.path.length === 0 && isDriveLetter(buffer, false))\n"
    "                buffer = buffer[0] + ':';\n"
    "              url.path.push(buffer);\n"
    "            }\n"
    "            buffer = '';\n"
    "            if (c === 0x3F) { url.query = ''; state = S_QUERY; }\n"
    "            if (c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "          } else buffer += encodeCP(c, inPath);\n"
    "          break;\n"
    "        case S_OPAQUE_PATH:\n"
    "          if (c === 0x3F) { url.query = ''; state = S_QUERY; }\n"
    "          else if (c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "          else if (c === 0x20) {\n"
    "            const next = p + 1 < len ? cps[p + 1] : EOF;\n"
    "            url.path += next === 0x3F || next === 0x23 ? '%20' : ' ';\n"
    "          } else if (c !== EOF) url.path += encodeCP(c, inC0);\n"
    "          break;\n"
    "        case S_QUERY:\n"
    "          if ((!override && c === 0x23) || c === EOF) {\n"
    "            url.query += encodeString(buffer, special ? inSpecialQuery : inQuery);\n"
    "            buffer = '';\n"
    "            if (c === 0x23) { url.fragment = ''; state = S_FRAGMENT; }\n"
    "          } else if (c !== EOF) buffer += fromCP(c);\n"
    "          break;\n"
    "        case S_FRAGMENT:\n"
    "          if (c !== EOF) url.fragment += encodeCP(c, inFragment);\n"
    "          break;\n"
    "      }\n"
    "      if (p >= len) break;\n"
    "    }\n"
    "    return url;\n"
    "  }\n"
    "  function serializePath(u) {\n"
    "    if (hasOpaquePath(u)) return u.path;\n"
    "    let out = '';\n"
    "    for (const seg of u.path) out += '/' + seg;\n"
    "    return out;\n"
    "  }\n"
    "  function serialize(u, excludeFragment) {\n"
    "    let out = u.scheme + ':';\n"
    "    if (u.host !== null) {\n"
    "      out += '//';\n"
    "      if (includesCredentials(u)) {\n"
    "        out += u.username;\n"
    "        if (u.password !== '') out += ':' + u.password;\n"
    "        out += '@';\n"
    "      }\n"
    "      out += u.host;\n"
    "      if (u.port !== null) out += ':' + u.port;\n"
    "    }\n"
    "    if (u.host === null && !hasOpaquePath(u) && u.path.length > 1 && u.path[0] === '') out += '/.';\n"
    "    out += serializePath(u);\n"
    "    if (u.query !== null) out += '?' + u.query;\n"
    "    if (!excludeFragment && u.fragment !== null) out += '#' + u.fragment;\n"
    "    return out;\n"
    "  }\n"
    "  function origin(u) {\n"
    "    switch (u.scheme) {\n"
    "      case 'blob': {\n"
    "        const inner = parse(serializePath(u));\n"
    "        if (inner && (inner.scheme === 'http' || inner.scheme === 'https')) return origin(inner);\n"
    "        return 'null';\n"
    "      }\n"
    "      case 'ftp': case 'http': case 'https': case 'ws': case 'wss':\n"
    "        return u.scheme + '://' + u.host + (u.port !== null ? ':' + u.port : '');\n"
    "      default:\n"
    "        return 'null';\n"
    "    }\n"
    "  }\n"
    "  function parse(input, baseString) {\n"
    "    let base = null;\n"
    "    if (baseString !== undefined) {\n"
    "      base = basicParse(baseString, null);\n"
    "      if (base === FAILURE) return FAILURE;\n"
    "    }\n"
    "    return basicParse(input, base);\n"
    "  }\n"
    "  function formParse(s) {\n"
    "    const out = [];\n"
    "    for (const seq of s.split('&')) {\n"
    "      if (seq === '') continue;\n"
    "      const eq = seq.indexOf('=');\n"
    "      let name = eq < 0 ? seq : seq.slice(0, eq), value = eq < 0 ? '' : seq.slice(eq + 1);\n"
    "      name = utf8Decode(percentDecode(utf8Encode(name.replace(/\\+/g, ' '))));\n"
    "      value = utf8Decode(percentDecode(utf8Encode(value.replace(/\\+/g, ' '))));\n"
    "      out.push([name, value]);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  function formEncode(s) {\n"
    "    let out = '';\n"
    "    for (const b of utf8Encode(s)) {\n"
    "      if (b === 0x20) out += '+';\n"
    "      else if (inForm(b)) out += pctByte(b);\n"
    "      else out += String.fromCharCode(b);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  function formSerialize(list) {\n"
    "    let out = '';\n"
    "    for (let i = 0; i < list.length; i++) {\n"
    "      if (i) out += '&';\n"
    "      out += formEncode(list[i][0]) + '=' + formEncode(list[i][1]);\n"
    "    }\n"
    "    return out;\n"
    "  }\n"
    "  const need = (n, got, what) => {\n"
    "    if (got < n) throw new TypeError(what + ': ' + n + ' argument(s) required, but only ' + got + ' present');\n"
    "  };\n"
    "  let linkParams; // (params, url) -> void, set below (the classes share private state through it)\n"
    "  let setParamsList; // (params, list) -> void\n"
    "  class URLSearchParams {\n"
    "    #list = [];\n"
    "    #url = null; // the URL object this belongs to, if any\n"
    "    constructor(init = '') {\n"
    "      if (init !== null && (typeof init === 'object' || typeof init === 'function')) {\n"
    "        const iter = init[Symbol.iterator];\n"
    "        if (iter !== undefined && iter !== null) {\n"
    "          if (typeof iter !== 'function') throw new TypeError('URLSearchParams: the init object is not iterable');\n"
    "          for (const pair of init) {\n"
    "            if (pair === null || (typeof pair !== 'object' && typeof pair !== 'function'))\n"
    "              throw new TypeError('URLSearchParams: each pair must be a sequence of two strings');\n"
    "            const a = [...pair];\n"
    "            if (a.length !== 2) throw new TypeError('URLSearchParams: each pair must hold exactly two items');\n"
    "            this.#list.push([usv(a[0]), usv(a[1])]);\n"
    "          }\n"
    "        } else {\n"
    "          for (const key of Reflect.ownKeys(init)) {\n"
    "            const d = Reflect.getOwnPropertyDescriptor(init, key);\n"
    "            if (d === undefined || !d.enumerable) continue;\n"
    "            if (typeof key === 'symbol') continue;\n"
    "            this.#list.push([usv(key), usv(init[key])]);\n"
    "          }\n"
    "        }\n"
    "      } else {\n"
    "        let s = usv(init);\n"
    "        if (s[0] === '?') s = s.slice(1);\n"
    "        this.#list = formParse(s);\n"
    "      }\n"
    "    }\n"
    "    static {\n"
    "      linkParams = (params, url) => { params.#url = url; };\n"
    "      setParamsList = (params, list) => { params.#list = list; };\n"
    "    }\n"
    "    #update() {\n"
    "      if (this.#url === null) return;\n"
    "      const s = formSerialize(this.#list);\n"
    "      urlSetQuery(this.#url, s === '' ? null : s);\n"
    "    }\n"
    "    get size() { return this.#list.length; }\n"
    "    append(name, value) {\n"
    "      need(2, arguments.length, 'URLSearchParams.append');\n"
    "      this.#list.push([usv(name), usv(value)]);\n"
    "      this.#update();\n"
    "    }\n"
    "    delete(name, value) {\n"
    "      need(1, arguments.length, 'URLSearchParams.delete');\n"
    "      name = usv(name);\n"
    "      const v = value === undefined ? undefined : usv(value);\n"
    "      this.#list = this.#list.filter(([n, x]) => !(n === name && (v === undefined || x === v)));\n"
    "      this.#update();\n"
    "    }\n"
    "    get(name) {\n"
    "      need(1, arguments.length, 'URLSearchParams.get');\n"
    "      name = usv(name);\n"
    "      for (const [n, v] of this.#list) if (n === name) return v;\n"
    "      return null;\n"
    "    }\n"
    "    getAll(name) {\n"
    "      need(1, arguments.length, 'URLSearchParams.getAll');\n"
    "      name = usv(name);\n"
    "      const out = [];\n"
    "      for (const [n, v] of this.#list) if (n === name) out.push(v);\n"
    "      return out;\n"
    "    }\n"
    "    has(name, value) {\n"
    "      need(1, arguments.length, 'URLSearchParams.has');\n"
    "      name = usv(name);\n"
    "      const v = value === undefined ? undefined : usv(value);\n"
    "      for (const [n, x] of this.#list) if (n === name && (v === undefined || x === v)) return true;\n"
    "      return false;\n"
    "    }\n"
    "    set(name, value) {\n"
    "      need(2, arguments.length, 'URLSearchParams.set');\n"
    "      name = usv(name);\n"
    "      value = usv(value);\n"
    "      const i = this.#list.findIndex(([n]) => n === name);\n"
    "      if (i < 0) this.#list.push([name, value]);\n"
    "      else {\n"
    "        this.#list[i][1] = value;\n"
    "        this.#list = this.#list.filter(([n], j) => j <= i || n !== name);\n"
    "      }\n"
    "      this.#update();\n"
    "    }\n"
    "    sort() {\n"
    "      this.#list = this.#list\n"
    "        .map((p, i) => [p, i])\n"
    "        .sort((a, b) => (a[0][0] < b[0][0] ? -1 : a[0][0] > b[0][0] ? 1 : a[1] - b[1]))\n"
    "        .map(x => x[0]);\n"
    "      this.#update();\n"
    "    }\n"
    "    toString() { return formSerialize(this.#list); }\n"
    "    forEach(fn, thisArg) {\n"
    "      need(1, arguments.length, 'URLSearchParams.forEach');\n"
    "      if (typeof fn !== 'function') throw new TypeError('URLSearchParams.forEach: the callback is not a function');\n"
    "      for (let i = 0; i < this.#list.length; i++) fn.call(thisArg, this.#list[i][1], this.#list[i][0], this);\n"
    "    }\n"
    "    *entries() { for (let i = 0; i < this.#list.length; i++) yield [this.#list[i][0], this.#list[i][1]]; }\n"
    "    *keys() { for (let i = 0; i < this.#list.length; i++) yield this.#list[i][0]; }\n"
    "    *values() { for (let i = 0; i < this.#list.length; i++) yield this.#list[i][1]; }\n"
    "  }\n"
    "  Object.defineProperty(URLSearchParams.prototype, Symbol.iterator, {\n"
    "    value: URLSearchParams.prototype.entries, writable: true, configurable: true,\n"
    "  });\n"
    "  Object.defineProperty(URLSearchParams.prototype, Symbol.toStringTag, { value: 'URLSearchParams', configurable: true });\n"
    "  let urlSetQuery; // (url, query or null) -> void, for URLSearchParams' updates\n"
    "  class URL {\n"
    "    #u;\n"
    "    #params;\n"
    "    constructor(url, base) {\n"
    "      need(1, arguments.length, 'URL');\n"
    "      const r = parse(usv(url), base === undefined ? undefined : usv(base));\n"
    "      if (r === FAILURE) throw new TypeError('Invalid URL: ' + usv(url));\n"
    "      this.#u = r;\n"
    "      this.#params = new URLSearchParams(r.query === null ? '' : r.query);\n"
    "      linkParams(this.#params, this);\n"
    "    }\n"
    "    static {\n"
    "      urlSetQuery = (url, q) => { url.#u.query = q; };\n"
    "    }\n"
    "    static parse(url, base) {\n"
    "      need(1, arguments.length, 'URL.parse');\n"
    "      try { return new URL(url, base); } catch (e) { return null; }\n"
    "    }\n"
    "    static canParse(url, base) {\n"
    "      need(1, arguments.length, 'URL.canParse');\n"
    "      return parse(usv(url), base === undefined ? undefined : usv(base)) !== FAILURE;\n"
    "    }\n"
    "    get href() { return serialize(this.#u); }\n"
    "    set href(v) {\n"
    "      const r = parse(usv(v));\n"
    "      if (r === FAILURE) throw new TypeError('Invalid URL: ' + usv(v));\n"
    "      this.#u = r;\n"
    "      setParamsList(this.#params, r.query === null ? [] : formParse(r.query));\n"
    "    }\n"
    "    get origin() { return origin(this.#u); }\n"
    "    get protocol() { return this.#u.scheme + ':'; }\n"
    "    set protocol(v) { basicParse(usv(v) + ':', null, this.#u, S_SCHEME_START); }\n"
    "    get username() { return this.#u.username; }\n"
    "    set username(v) {\n"
    "      if (cannotHaveCredentialsOrPort(this.#u)) return;\n"
    "      this.#u.username = encodeString(usv(v), inUserinfo);\n"
    "    }\n"
    "    get password() { return this.#u.password; }\n"
    "    set password(v) {\n"
    "      if (cannotHaveCredentialsOrPort(this.#u)) return;\n"
    "      this.#u.password = encodeString(usv(v), inUserinfo);\n"
    "    }\n"
    "    get host() {\n"
    "      const u = this.#u;\n"
    "      if (u.host === null) return '';\n"
    "      return u.port === null ? u.host : u.host + ':' + u.port;\n"
    "    }\n"
    "    set host(v) {\n"
    "      if (hasOpaquePath(this.#u)) return;\n"
    "      basicParse(usv(v), null, this.#u, S_HOST);\n"
    "    }\n"
    "    get hostname() { return this.#u.host === null ? '' : this.#u.host; }\n"
    "    set hostname(v) {\n"
    "      if (hasOpaquePath(this.#u)) return;\n"
    "      basicParse(usv(v), null, this.#u, S_HOSTNAME);\n"
    "    }\n"
    "    get port() { return this.#u.port === null ? '' : String(this.#u.port); }\n"
    "    set port(v) {\n"
    "      if (cannotHaveCredentialsOrPort(this.#u)) return;\n"
    "      v = usv(v);\n"
    "      if (v === '') this.#u.port = null;\n"
    "      else basicParse(v, null, this.#u, S_PORT);\n"
    "    }\n"
    "    get pathname() { return serializePath(this.#u); }\n"
    "    set pathname(v) {\n"
    "      if (hasOpaquePath(this.#u)) return;\n"
    "      this.#u.path = [];\n"
    "      basicParse(usv(v), null, this.#u, S_PATH_START);\n"
    "    }\n"
    "    get search() {\n"
    "      const q = this.#u.query;\n"
    "      return q === null || q === '' ? '' : '?' + q;\n"
    "    }\n"
    "    set search(v) {\n"
    "      v = usv(v);\n"
    "      const u = this.#u;\n"
    "      if (v === '') {\n"
    "        u.query = null;\n"
    "        setParamsList(this.#params, []);\n"
    "        return;\n"
    "      }\n"
    "      const input = v[0] === '?' ? v.slice(1) : v;\n"
    "      u.query = '';\n"
    "      basicParse(input, null, u, S_QUERY);\n"
    "      setParamsList(this.#params, formParse(input));\n"
    "    }\n"
    "    get searchParams() { return this.#params; }\n"
    "    get hash() {\n"
    "      const f = this.#u.fragment;\n"
    "      return f === null || f === '' ? '' : '#' + f;\n"
    "    }\n"
    "    set hash(v) {\n"
    "      v = usv(v);\n"
    "      const u = this.#u;\n"
    "      if (v === '') {\n"
    "        u.fragment = null;\n"
    "        return;\n"
    "      }\n"
    "      u.fragment = '';\n"
    "      basicParse(v[0] === '#' ? v.slice(1) : v, null, u, S_FRAGMENT);\n"
    "    }\n"
    "    toString() { return serialize(this.#u); }\n"
    "    toJSON() { return serialize(this.#u); }\n"
    "  }\n"
    "  Object.defineProperty(URL.prototype, Symbol.toStringTag, { value: 'URL', configurable: true });\n"
    "  return { URL, URLSearchParams };\n"
    "})\n";
